- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
- **Issue or task referred:** UI-13
I added some templates to make simpler providing additional information in GitHub
> [UI-13] Set up templates for GitHub

- packages/progress-bar/tests/ProgressBar.test.js
- packages/progress-bar/tests/__snapshots__/ProgressBar.test.js.snap
- They are calling ProgressBar with incorrect value
> Remove broken `ProgressBar` unit tests

- packages/combo-box/tests/ComboBox.test.js
- packages/combo-box/tests/Dropdown.test.js
- packages/combo-box/tests/__snapshots__/Dropdown.test.js.snap
- packages/rating/README.md
- packages/rating/index.js
- packages/rating/package.json
- packages/rating/src/Rating.js
- packages/rating/stories.js
- packages/rating/styles/config.sass
- packages/rating/styles/geometry.sass
- packages/rating/styles/main.sass
- packages/rating/styles/theming.sass
- packages/rating/tests/Rating.test.js
- packages/rating/tests/__snapshots__/Rating.test.js.snap
- **Issue or task referred:** UI-46
Add component for Rating representation, we will need it soon.
> [UI-46] Add component for Rating representation

- .circleci/config.yml
- package-lock.json
- package.json
- scripts/runTests.js
Process test results in CircleCI.
> Process test results in CircleCI

- packages/shared/styles/config/colors.sass
- packages/shared/styles/config/grid.sass
- packages/shared/styles/config/rwd.sass
- packages/shared/styles/config/typography.sass
- packages/shared/styles/config/various.sass
- **Issue or task referred:** UI-49, UI-50
Update shared configuration to use `!default` flag for easier overrides.
> Add !default flags to all shared configuration variables

- packages/shared/styles/config/colors.sass
- packages/shared/styles/config/grid.sass
- packages/shared/styles/config/rwd.sass
- packages/shared/styles/config/typography.sass
- packages/shared/styles/config/various.sass
- packages/typography/index.js
Exported omitted `Lead` component from `@talixo/typography` package.
> Export Lead component from @talixo/typography

- packages/progress-ring/src/ProgressRing.js
- packages/progress-ring/tests/ProgressRing.test.js
- packages/progress-ring/tests/__snapshots__/ProgressRing.test.js.snap
Fix indeterminate progress ring view.
> Fix progress ring with indeterminate state

- packages/icon/styles/geometry.sass
Fix `@talixo/icon` to make it working properly with Material Icons
> Fix `@talixo/icon` to make it working properly with Material Icons

- packages/list/stories.js
- packages/list/styles/geometry.sass
- **Component affected:** List
Add RTL support for List component.
> Add RTL support for List component

- packages/number-input/README.md
- packages/number-input/src/NumberInput.js
- packages/number-input/src/NumberInputStepper.js
- packages/number-input/stories.js
- packages/number-input/styles/geometry.sass
- packages/number-input/tests/NumberInput.test.js
- packages/number-input/tests/NumberInputStepper.test.js
- packages/number-input/tests/__snapshots__/NumberInput.test.js.snap
- packages/number-input/tests/__snapshots__/NumberInputStepper.test.js.snap
- **Components affected:** NumberInput
Sorry, that it includes Calendar and ComboBox, but I am doing changes right now on real-life project and there is a lot of issues which should be fixed before.
- Add possibility to switch off stepper in number input
- Improve accessibility of number input by allowing Spacebar hitting buttons
- Fix default props of Number Input
> NumberInput improvements

- package-lock.json
- packages/shared/story.js
- **Component affected:** All with controlled stories
Adding `propTablesExclude` in controlled stories did't exclude chosen components.
> Bugfix / Fix tables in controlled stories

- packages/form/README.md
- packages/form/index.js
- packages/form/package.json
- packages/form/src/Form.js
- packages/form/stories.js
- packages/form/styles/config.sass
- packages/form/styles/geometry.sass
- packages/form/styles/main.sass
- packages/form/styles/theming.sass
- packages/form/tests/Form.test.js
- packages/form/tests/__snapshots__/Form.test.js.snap
- **Issue or task referred:** UI-42
It is a simple form component with footer created according to provided mocks.
> [UI-42] form wrapper

- packages/data-table/.npmignore
- packages/data-table/README.md
- packages/data-table/index.js
- packages/data-table/package.json
- packages/data-table/src/DataTable.js
- packages/data-table/src/TableHeaders.js
- packages/data-table/src/TableRow.js
- packages/data-table/stories.js
- packages/data-table/styles/config.sass
- packages/data-table/styles/geometry.sass
- packages/data-table/styles/main.sass
- packages/data-table/styles/theming.sass
- packages/data-table/tests/DataTable.test.js
- packages/data-table/tests/TableHeaders.test.js
- packages/data-table/tests/TableRow.test.js
- packages/data-table/tests/__snapshots__/DataTable.test.js.snap
- packages/data-table/tests/__snapshots__/TableHeaders.test.js.snap
- packages/data-table/tests/__snapshots__/TableRow.test.js.snap
- packages/data-table/tests/fixtures/testData.js
- wallaby.js
- **Issue or task referred:** UI-57
I have created component which generates table from provided data. Additionally it handles sorting data inside tables, row actions and custom cells and headers.
> [UI-57] Data tables

- packages/divider/.npmignore
- packages/divider/README.md
- packages/divider/index.js
- packages/divider/package.json
- packages/divider/src/Divider.js
- packages/divider/stories.js
- packages/divider/styles/config.sass
- packages/divider/styles/geometry.sass
- packages/divider/styles/main.sass
- packages/divider/tests/Divider.test.js
- packages/divider/tests/__snapshots__/Divider.test.js.snap
- **Issue or task referred:** UI-61
I have created component which can be use to divide sections of page or elements
> [UI-61] Divider component.

- packages/country-flag/stories.js
- **Issue or task referred:** #69
> #69: Change `CountryFlag` story to show usage of parent font size

- package-lock.json
- packages/combo-box/README.md
- packages/combo-box/src/AutoComplete.js
- packages/combo-box/src/ComboBox.js
- packages/combo-box/src/Menu.js
- packages/combo-box/src/SelectBox.js
- packages/combo-box/stories.js
- packages/combo-box/styles/config.sass
- packages/combo-box/styles/main.sass
- packages/combo-box/tests/Menu.test.js
- packages/combo-box/tests/__snapshots__/ComboBox.test.js.snap
- packages/combo-box/tests/__snapshots__/Menu.test.js.snap
- packages/combo-box/tests/__snapshots__/SelectBox.test.js.snap
… & Readme
- **Issue or task referred:** UI-71
I added possibility to add footer into Autocomplete list. User should pass node as prop.
> [UI-71] Add footer feature to Combobox

- packages/options-input/README.md
- packages/options-input/src/Option.js
- packages/options-input/src/OptionsInput.js
- packages/options-input/src/OptionsInputValue.js
- packages/options-input/stories.js
- packages/options-input/styles/config.sass
- packages/options-input/styles/main.sass
- packages/options-input/tests/Option.test.js
- packages/options-input/tests/OptionTooltipContent.test.js
- packages/options-input/tests/OptionsInputValue.test.js
- packages/options-input/tests/__snapshots__/OptionTooltipContent.test.js.snap
- packages/options-input/tests/__snapshots__/OptionsInput.test.js.snap
- packages/options-input/tests/__snapshots__/OptionsInputValue.test.js.snap
- **Issue or task referred:** LP-58
Added possibility to make some options visible even if their value is 0: 
- Added props handling
- Added proper styling
- Updated tests which were written incorrectly
> [UI] Add possibility to make 0 value options visible in OptionsInput

- packages/countdown/stories.js
- **Issue or task referred:** UI-72
Fix story in Countdown with custom format.
> [UI-72] Fix Countdown story with custom format

- package-lock.json
- packages/combo-box/stories.js
- packages/masked-input/stories.js
- packages/phone-input/README.md
- packages/phone-input/stories.js
- **Issue or task referred:** UI-73
Added CountryFlagsProvider to stories which use PhoneInput.
> [UI-73] Add CountryFlagsProvider to stories which use PhoneInput

- packages/combo-box/README.md
- packages/combo-box/src/SelectBox.js
- packages/combo-box/src/SelectBoxValue.js
- packages/phone-input/src/PhoneInput.js
- packages/phone-input/tests/__snapshots__/PhoneInput.test.js.snap
- **Issue or task referred:** UI-83
Disallow focusing countries list in PhoneInput by keyboard
> [UI-83] Disallow focusing countries list in PhoneInput by keyboard

- packages/checkbox/styles/config.sass
- packages/radio-input/styles/config.sass
- **Issue or task referred:** UI-85
Add styling variable for tick ratio both for radio & checkbox inputs
> [UI-85] Add styling variable for tick ratio both for radio & checkbox inputs

- packages/form-handler/src/FormHandler.js
- **Issue or task referred:** UI-88
Fix error handling in FormHandler.
> [UI-88] Fix error handling in FormHandler

- packages/credit-card/tests/__snapshots__/CreditCardInput.test.js.snap
- packages/form-field/README.md
- packages/form-field/src/FormField.js
- packages/form-field/stories.js
- packages/form-field/tests/__snapshots__/FormField.test.js.snap
- packages/form-handler/README.md
- packages/form-handler/src/FormHandler.js
- **Issue or task referred:** UI-81
Added error/warning message formatters for `FormField` and `FormHandler`
>  [UI-81] Add error/warning message formatters for FormField/Handler

- packages/options-input/styles/config.sass
- **Issue or task referred:** UI-87
Adjust default spacing of options input icon
> [UI-87] Adjust default spacing of options input icon

- packages/masked-input/README.md
- packages/masked-input/src/MaskedInput.js
- packages/masked-input/stories.js
- packages/masked-input/tests/MaskedInput.test.js
- **Issue or task referred:** UI-77
Set input in MaskedInput through `children` property
> [UI-77] Set input in MaskedInput through `children` property

- packages/checkbox/src/Checkbox.js
- packages/checkbox/styles/config.sass
- packages/checkbox/styles/main.sass
- packages/checkbox/tests/__snapshots__/Checkbox.test.js.snap
- packages/radio-input/styles/config.sass
- **Issue or task referred:** UI-80
Handle focus on Checkboxes.
> [UI-80] Handle focus on Checkboxes

- packages/calendar/src/Calendar.js
- packages/calendar/tests/Calendar.test.js
- **Issue or task referred:** UI-82
Improve Calendar update feedback
> [UI-82] Fix Calendar to have onChange feedback sent correctly

- packages/checkbox-group/README.md
- packages/checkbox-group/index.js
- packages/checkbox-group/package.json
- packages/checkbox-group/src/CheckboxGroup.js
- packages/checkbox-group/stories.js
- packages/checkbox-group/styles/config.sass
- packages/checkbox-group/tests/CheckboxGroup.test.js
- packages/checkbox-group/tests/__snapshots__/CheckboxGroup.test.js.snap
- packages/radio-group/README.md
- **Issue or task referred:** UI-89
Add component for groups of checkboxes. First use case, which it will be used for, is a group of conditions checkboxes.
> [UI-89] Add component for groups of checkboxes

- packages/charts/package.json
- packages/credit-card/tests/__snapshots__/RangeInput.test.js.snap
- packages/number-input/styles/main.sass
- packages/options-input/stories.js
- packages/options-input/styles/config.sass
- packages/options-input/styles/main.sass
- packages/text-input/src/TextInput.js
- packages/text-input/styles/config.sass
- packages/text-input/styles/main.sass
- packages/text-input/tests/analyzeInput.test.js
- packages/text-input/tests/calculateInputStyles.test.js
- packages/text-input/utils/analyzeInput.js
- packages/text-input/utils/calculateInputStyles.js
- **Issue or task referred:** UI-94
Bug fixed: 
- TextInput position not positioned properly,
- TextInput suffix width does not calculate properly,
- OptionsInput suffixes not fully visible,
- OptionsInput RTL styles.
> [UI-94] Suffix not working correctly

- package-lock.json
- packages/map/tests/Map.test.js
- packages/map/tests/__snapshots__/Map.test.js.snap
- **Issue or task referred:** UI-100
Fix Map unit tests.
> [UI-100] Fix Map unit tests

- packages/credit-card/tests/__snapshots__/RangeInput.test.js.snap
- packages/text-input/src/TextInput.js
- packages/text-input/utils/calculateInputStyles.js
- **Issue or task referred:** UI-103
Text input performance optimized.
- reduced number of renders after an update,
- reduced number of events dispatched after updating the input value
> [UI-103] Text input performance optimized.

- packages/modal/README.md
- packages/modal/src/Modal.js
- packages/modal/stories.js
- packages/modal/tests/Modal.test.js
- packages/modal/tests/__snapshots__/Modal.test.js.snap
- **Issue or task referred:** UI-104
Added onClick event handler to a modal backdrop.
> [UI-104] Added event handler to modal backdrop.

- packages/phone-input/README.md
- packages/phone-input/src/PhoneInput.js
- **Issue or task referred:** UI-105
Added possibility to pass autoComplete prop to PhoneInput.
> [UI-105] Added possibility to pass autoComplete prop to phone input

- packages/combo-box/src/AutoComplete.js
- packages/credit-card/tests/__snapshots__/RangeInput.test.js.snap
- packages/form/src/Field.js
- packages/form/tests/__snapshots__/FormHandler.test.js.snap
- packages/masked-input/src/MaskedInput.js
- **Issue or task referred:** UI-109
AutoComplete, Field, and MaskedInput fixed to pass name prop.
> [UI-109] AutoComplete, Field, and MaskedInput fixed to pass name prop.

- packages/time-picker/src/TimeInput.js
- packages/time-picker/styles/main.sass
- packages/time-picker/tests/__snapshots__/TimeInput.test.js.snap
- **Issue or task referred:** UI-108
> [UI-108] Hide time picker by arrow

- packages/calendar/styles/main.sass
- packages/options-input/src/OptionsInput.js
- packages/options-input/styles/main.sass
- packages/options-input/tests/__snapshots__/OptionsInput.test.js.snap
- Fix calendar to look good on Safari
- Fix options input to make toggling arrow working on Safari
> [LP-140] Fixes for Safari

- package-lock.json
- packages/timeline/.npmignore
- packages/timeline/README.md
- packages/timeline/index.js
- packages/timeline/package.json
- packages/timeline/src/Timeline.js
- packages/timeline/src/TimelineElement.js
- packages/timeline/src/TimelineLine.js
- packages/timeline/src/TimelinePoint.js
- packages/timeline/stories.js
- packages/timeline/styles/config.sass
- packages/timeline/styles/main.sass
- packages/timeline/tests/Timeline.test.js
- packages/timeline/tests/TimelineElement.test.js
- packages/timeline/tests/TimelineLine.test.js
- packages/timeline/tests/TimelinePoint.test.js
- packages/timeline/tests/__snapshots__/Timeline.test.js.snap
- packages/timeline/tests/__snapshots__/TimelineElement.test.js.snap
- packages/timeline/tests/__snapshots__/TimelineLine.test.js.snap
- packages/timeline/tests/__snapshots__/TimelinePoint.test.js.snap
- **Issue or task referred:** UI-128
Timeline component, which show start time, end time and optionally ride time with the appropriate
icons.
> [UI-128] Timeline component

- package.json
- packages/tooltip/README.md
- packages/tooltip/package.json
- **Issue or task referred:** UI-119
Update library (react-instantiable-stateless)  to newest version
> [UI-119] Update library to newest version

- package-lock.json
- packages/columns/.npmignore
- packages/columns/README.md
- packages/columns/index.js
- packages/columns/package.json
- packages/columns/src/Columns.js
- packages/columns/src/ColumnsElement.js
- packages/columns/stories.js
- packages/columns/styles/config.sass
- packages/columns/styles/main.sass
- packages/columns/tests/Columns.test.js
- packages/columns/tests/ColumnsElement.test.js
- packages/columns/tests/__snapshots__/Columns.test.js.snap
- packages/columns/tests/__snapshots__/ColumnsElement.test.js.snap
- **Issue or task referred:** UI-125
Columns component which display content in columns with equal width. Additionally user can specify how many columns in row will be displayed.
> [UI-125] create component for column based sections

- packages/accordion/README.md
- packages/accordion/src/Accordion.js
- packages/accordion/stories.js
- **Issue or task referred:** UI-118
Add possibility to set custom animationTime for accordion element
> [UI-118] Add possibility to set custom animationTime for accordion element

- packages/radio-group/src/RadioGroup.js
- packages/radio-group/stories.js
- packages/radio-group/tests/RadioGroup.test.js
- packages/radio-group/tests/__snapshots__/RadioGroup.test.js.snap
- **Issue or task referred:** UI-117
Now allow null value passed in options.
> [UI-117] Allow null value passed in options

- packages/price/src/formatters.js
- packages/price/tests/Price.test.js
- packages/wizard/src/Wizard.js
- packages/wizard/stories.js
- **Issue or task referred:** UI-137
Fix issue with Wizard in FormHandler
> [UI-137] Fix issue with Wizard in FormHandler

- packages/data-table/stories.js
- **Issue or task referred:** #197 
> Fix DataTable story to correct close notification button

- packages/calendar/styles/main.sass
- packages/masked-input/tests/__snapshots__/MaskedInput.test.js.snap
- **Issue or task referred:** UI-141
I have change styling to get rid of a problem when using the calendar component.
From:
To:
> [UI-141] Fix calendar styles

- packages/switcher/styles/main.sass
- **Issue or task referred:** UI-10
> [UI-146] Use bg color variable in component styles

- packages/switcher/styles/config.sass
- packages/switcher/styles/main.sass
- **Issue or task referred:** UI-10
> [UI-147] Expose trasnsition variable for switcher

- packages/notification/styles/config.sass
- packages/notification/styles/main.sass
- **Issue or task referred:** UI-10
> [UI-148] Expose notification transition as a variable

- packages/calendar/README.md
- packages/calendar/package.json
- packages/calendar/styles/main.sass
- **Issue or task referred:** UI-143
Update react dates varsion to the newest, update styles and class names
> [UI-143] Update react dates varsion to the newest, update styles and class names
